export default {
  COLOR_PRIMARY: "#49BEAA",
  COLOR_PRIMARY_SUB: "#49DCB1",
  COLOR_SECONDARY: "#456990",
  COLOR_RED: "#EF767A",
  COLOR_WHITE: "#FFF",
  COLOR_BLACK: "#3F414A",

  PADDING_SCREEN: 20,
  PADDING_SMALL: 10,
  PADDING_MEDIUM: 15,
  PADDING_LARGE: 20,
  PADDING_EXTRA_LARGE: 30,

  MARGIN_SMALL: 10,
  MARGIN_MEDIUM: 15,
  MARGIN_LARGE: 20,
  MARGIN_EXTRA_LARGE: 30,

  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 15,
  FONT_SIZE_LARGE: 20,
  FONT_SIZE_EXTRA_LARGE: 30,
  FONT_SIZE_TITLE: 15,

  FONT_WEIGHT_LIGHT: 300,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_HEAVY: 900,
  FONT_WEIGHT_BOLD: "bold",

  FONT_FAMILY_LIGHT: "Comfortaa-Light",
  FONT_FAMILY_REGULAR: "Comfortaa-Regular",
  FONT_FAMILY_BOLD: "Comfortaa-Bold",

  INPUT_HEIGHT_SIZE: 40
};
